quick fix to handle BigNumbers array as argument of the event log
expected:
as ```[ BigNumber { _hex: '0x01f4' }, BigNumber { _hex: '0x01f4' } ]``` equals ```[ BigNumber { _hex: '0x01f4' }, BigNumber { _hex: '0x01f4' } ]``` - it passes the test
actual:
```
AssertionError: expected [ Array(2) ] to equal [ Array(2) ]
    at assertArgsArraysEqual (src/test/productAssetIdentity.spec.ts:65:51)
    at derivedPromise.promise.then (src/test/productAssetIdentity.spec.ts:71:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
switching to deep.equal also doesn't solve the issue...

quick and dirty fix is to stringify the `actualArgs` and `expectedArgs` values of every argument within `withArgs` method.